<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXJ8oO2i\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXJ8oO2i/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXJ8oO2i.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXJ8oO2i\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXJ8oO2i\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XJ8oO2i',
    'container.build_id' => '964f7bc0',
    'container.build_time' => 1649909928,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXJ8oO2i');
